#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    skibidicode.php-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^skibidicode\.php\.ddev\.site$`)
      
      service: "skibidicode.php-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "skibidicode.php-redirectHttps"
    skibidicode.php-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^skibidicode\.php\.ddev\.site$`)
      
      service: "skibidicode.php-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "skibidicode.php-redirectHttps"
    
    
    
    skibidicode.php-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^skibidicode\.php\.ddev\.site$`)
      
      service: "skibidicode.php-web-80"
      ruleSyntax: v3
      
      tls: true
      
    skibidicode.php-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^skibidicode\.php\.ddev\.site$`)
      
      service: "skibidicode.php-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    skibidicode.php-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    skibidicode.php-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-skibidicode.php-web:80
        
    skibidicode.php-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-skibidicode.php-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/skibidicode.php.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/skibidicode.php.key